# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_users_assets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cosmospy._interfaces.gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18model_users_assets.proto\x12"dexilon_exchange.dexilonl2.trading\x1a\ngogo.proto"\xbd\x02\n\x0bUsersAssets\x12\x16\n\x0e\x61\x63\x63ountAddress\x18\x01 \x01(\t\x12\r\n\x05\x61sset\x18\x02 \x01(\t\x12@\n\x08leverage\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12?\n\x07\x62\x61lance\x18\x04 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\x45\n\rlockedBalance\x18\x05 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12=\n\x05price\x18\x06 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x42\x37Z5github.com/dexilon-exchange/dexilonL2/x/trading/typesb\x06proto3'
)


_USERSASSETS = DESCRIPTOR.message_types_by_name["UsersAssets"]
UsersAssets = _reflection.GeneratedProtocolMessageType(
    "UsersAssets",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERSASSETS,
        "__module__": "model_users_assets_pb2"
        # @@protoc_insertion_point(class_scope:dexilon_exchange.dexilonl2.trading.UsersAssets)
    },
)
_sym_db.RegisterMessage(UsersAssets)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z5github.com/dexilon-exchange/dexilonL2/x/trading/types"
    )
    _USERSASSETS.fields_by_name["leverage"]._options = None
    _USERSASSETS.fields_by_name[
        "leverage"
    ]._serialized_options = (
        b"\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000"
    )
    _USERSASSETS.fields_by_name["balance"]._options = None
    _USERSASSETS.fields_by_name[
        "balance"
    ]._serialized_options = (
        b"\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000"
    )
    _USERSASSETS.fields_by_name["lockedBalance"]._options = None
    _USERSASSETS.fields_by_name[
        "lockedBalance"
    ]._serialized_options = (
        b"\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000"
    )
    _USERSASSETS.fields_by_name["price"]._options = None
    _USERSASSETS.fields_by_name[
        "price"
    ]._serialized_options = (
        b"\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000"
    )
    _USERSASSETS._serialized_start = 77
    _USERSASSETS._serialized_end = 394
# @@protoc_insertion_point(module_scope)
