# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_trading_balance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmodel_trading_balance.proto\x12\"dexilon_exchange.dexilonL2.trading\x1a\ngogo.proto\"x\n\x0eTradingBalance\x12\x16\n\x0e\x61\x63\x63ountAddress\x18\x01 \x01(\t\x12?\n\x07\x62\x61lance\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\r\n\x05\x61sset\x18\x03 \x01(\tB7Z5github.com/dexilon-exchange/dexilonL2/x/trading/typesb\x06proto3')



_TRADINGBALANCE = DESCRIPTOR.message_types_by_name['TradingBalance']
TradingBalance = _reflection.GeneratedProtocolMessageType('TradingBalance', (_message.Message,), {
  'DESCRIPTOR' : _TRADINGBALANCE,
  '__module__' : 'model_trading_balance_pb2'
  # @@protoc_insertion_point(class_scope:dexilon_exchange.dexilonL2.trading.TradingBalance)
  })
_sym_db.RegisterMessage(TradingBalance)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/dexilon-exchange/dexilonL2/x/trading/types'
  _TRADINGBALANCE.fields_by_name['balance']._options = None
  _TRADINGBALANCE.fields_by_name['balance']._serialized_options = b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'
  _TRADINGBALANCE._serialized_start=79
  _TRADINGBALANCE._serialized_end=199
# @@protoc_insertion_point(module_scope)
